# Generated by Django 4.2.1 on 2023-06-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_testcarsbrands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcarsbrands',
            name='variants',
        ),
    ]
