# Generated by Django 4.2.1 on 2023-05-31 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_cars_repair_cars_кilometers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField()),
                ('image', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.carbrand'),
        ),
    ]
