# Generated by Django 4.2.1 on 2023-06-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_repairhistory_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carqueue',
            name='car_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service_app.cars', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='carqueue',
            name='mechanic_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.personalprofile', verbose_name='Mechanic'),
        ),
    ]
