# Generated by Django 4.2.1 on 2023-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_remove_testcarsbrands_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carqueue',
            name='status',
            field=models.CharField(blank=True, choices=[('Awaiting To Take', 'Awaiting To Take'), ('Investigating Car', 'Investigating Car'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=20, null=True),
        ),
    ]
