# Generated by Django 4.2.1 on 2023-07-03 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_appusers_groups'),
        ('service_app', '0004_alter_carqueue_car_id_alter_carqueue_mechanic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesProfile',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('position', models.CharField(blank=True, choices=[('Mechanic', 'Mechanic'), ('Reciver', 'Reciver')], max_length=10, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='carqueue',
            name='mechanic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.employeesprofile', verbose_name='Mechanic'),
        ),
        migrations.DeleteModel(
            name='PersonalProfile',
        ),
    ]
