# Generated by Django 4.2.1 on 2023-05-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_rename_кilometers_cars_kilometers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='img',
            new_name='brand',
        ),
    ]
