# Generated by Django 4.2.1 on 2023-07-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_employeesprofile_alter_carqueue_mechanic_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesprofile',
            name='position',
        ),
    ]
