# Generated by Django 4.2.1 on 2023-05-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_rename_img_cars_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='registration_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
