# Generated by Django 4.2.1 on 2023-07-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_app', '0006_remove_employeesprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesprofile',
            name='user_id',
            field=models.OneToOneField(limit_choices_to={'is_customer': False}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
