# Generated by Django 4.2.1 on 2023-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_alter_cars_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
