# Generated by Django 4.2.1 on 2023-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_servicegallery_alter_carqueue_mechanic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='VIN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cars',
            name='kilometers',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicegallery',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
